### ISSUE TITLE
Provide 'support' for same entities with different namespaces

### ISSUE THREAD

**Issue by francescalb** [emmo-repo/EMMO-python#128]
We have to decide on how to tackle this problem and what EMMOpython should support  and not. 
As of now the ontology.get_by_label_all(xxx), will return all different xxx, also with different namespaces, but ontology.xxx will only return the first it finds. 

If both are present in different namespaces it should at least give a warning, and some way to decide which one to use.

Alternatively it should be impossible to import different domain ontologies if they have overlapping terms.

**Comment by jesper-friis** [comment]
Good point. For compatibility with Owlready2 and for convenience I think that it is preferable that `onto.xxx` only returns a single object. But I agree that we then should give a warning. The same is the case with `onto[xxx]`.

The names of the methods get_by_label() and get_by_label_all() are quite long. Would it make sense to rename them to get_one() and get(), respectively?

**Comment by francescalb** [comment]
I am not sure which is the smartest way to go about this. I think get_by_label and get_by_label_all are fine. However, if we want to always check if there are more than one of a specific class we would have to always run get_by_label_all. If so, we should change get_by_label to run get_by_labe_all and return depending on the result from this. 

However, I am not sure that is very smart. Would it not slow down the code very much if all entities should be checked every time? Especially when the ontology is big...

**Comment by jesper-friis** [comment]
Ok, so we will not check and warn. How can we make it easy to be explicit? Full IRI using the world already works:

    onto.world['http://emmo.info/emmo/middle/materials#EMMO_eb77076b_a104_42ac_a065_798b2d2809ad']

This is the only fully unique way to refer to an entity, but is not very convenient. 

Prefixing the label with the last component in the namespace would be more convenient 

    onto.materials.Atom
    onto.mydomain.Atom

and work in most cases. Should we implement it? 

This would require two changes:
- Update `get_by_label()` to recognise a namespace
- Patch `owlready2.namespace.Namespace` with a `__getattr__()` method that returns the entity with the given label in this namespace. 

For efficiency we could cache the namespaces in a dict

    onto.namespaces = {e.namespace.name: e.namespace for e in onto.get_entities()}

Unrelated to this, it seems that EMMO-python does not provide attribute access by name any more, like

    onto.EMMO_eb77076b_a104_42ac_a065_798b2d2809ad

That should probably also be fixed?

**Comment by francescalb** [comment]
This is a good suggestion. The exception in which it will not work needs to be well described in the documentation

**Comment by francescalb** [comment]
Has been solved a bit differently with prefixes in #439 .

onto.get_by_label('label', prefix='prefix') does return the correct entity.
