### ISSUE TITLE
Tool for publishing domain ontologies

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO-python#140]
Add a tool or set of tools that streamline the workflow of publishing an versioned ontology, like how EMMO is made available on GitHub pages: https://emmo-repo.github.io/ 

It would need a reasonable trade-off between flexibility and simplicity. Maybe it could be implemented as a single command-line tool with sub-commands like git.

**Comment by francescalb** [comment]
first: only support for github pages - try to make it in such a way that more wide support can be added later. 

a set of commands: look at emmo what is done there.
