### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by vit-smilauer** [emmo-repo/EMMO-python#15]
Hi,
in setup.py, please use setuptools instead of distutils.core. Distutils.core is obsolete and does not install owl files, unable to run examples under tests/. I attach both setup.py and MANIFEST files working for me, installing necessary files.

[setup+MANIFEST.zip](https://github.com/emmo-repo/EMMO-python/files/3804014/setup%2BMANIFEST.zip)

Best regards. Vit

**Comment by jesper-friis** [comment]
Thanks for the comments. Based on this, we have updated setup.py and MANIFEST.in in branch 1.0.0
