### ISSUE TITLE
Specify version ranges for dependencies

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMO-python#155]
It would be safer and more helpful for dependencies of `EMMO` if

1. Minimum versions are specified for dependencies; and
2. A range of versions are allowed for dependencies.

The latter can be achieved either via `~=` or `>=X.Y,<Z`, where, for example, Z = X + 1.

**Comment by francescalb** [comment]
Yes, we can do this. Owlready2 is in continuous development so the reason we actually started having a version dependency of owlready was that a bug was introduced in one version. Is there a way to specify owlready2 version 0.26-0.30 except 0.27 (example)?

**Comment by CasperWA** [comment]
> (...) Is there a way to specify owlready2 version 0.26-0.30 except 0.27 (example)?

Indeed there is :)

PEP reference for version specifiers: https://www.python.org/dev/peps/pep-0440/#version-specifiers
Generel reference to the requirements.txt file format: https://pip.pypa.io/en/stable/cli/pip_install/#requirements-file-format

So, for Owlready2, it would look something like:

`Owlready2>=0.26,!=0.27,<1.0` or `Owlready2~=0.26,!=0.27`

`~=X.Y.Z` means "the newest X.Y version", i.e., it's equivalent to `>=X.Y.Z,<X.(Y+1)`.
A similar thing applies to `~=X.Y`, which is equivalent to `>=X.Y,<(X+1)`.
