### ISSUE TITLE
licence does not work with metadata

### ISSUE THREAD

**Issue by francescalb** [emmo-repo/EMMO-python#157]
onto.metadata.licence(append('LGPL/CC')) 

Traceback (most recent call last):
  File "periodic-table.py", line 115, in <module>
    onto.metadata.licence.append(en(
  File "/home/francescab/python-environments-linux/emmopy/lib/python3.8/site-packages/owlready2/namespace.py", line 1239, in __getattr__
    values = [self.namespace.ontology._to_python(o, d) for o, d in self.namespace.world._get_triples_sp_od(self.storid, Prop.storid)]
AttributeError: 'NoneType' object has no attribute 'storid'

Test the commented out line in examples/periodic-table.py in branch peridic-table-example

**Comment by francescalb** [comment]
This is because license is defined, and not licence. Should be possible to use both american and british spelling I think

**Comment by jesper-friis** [comment]
The spelling depends on the ontology. I guess that you are using Dublin Core terms (http://purl.org/dc/terms/) which uses english spelling.

**Comment by francescalb** [comment]
No, I was using an EMMObased-ontology, so it is defined from there. My suggestions was only to have a check for if we licence is written in metadata it will be changed to license if that is defined. And if tou search for licence in metadata it will give the license  if that is defined and not licence. But it is a  picky thing, maybe not so important?

**Comment by jesper-friis** [comment]
I see. I think that we should leave it to the ontology to add language support, rather than doing it in EMMO-python. What happens if you add the American spelling to the license annotation attribute?

**Comment by francescalb** [comment]
Ok, then I will close this issue.
