### ISSUE TITLE
Missing https://emmc.info/emmo-inferred

### ISSUE THREAD

**Issue by vit-smilauer** [emmo-repo/EMMO-python#16]
Hi,
running demo/vertical/define_ontology.py ends up with an error. Minimum working example in Python3, just to demonstrate the problem.

from emmo import get_ontology
emmo = get_ontology()
emmo.load()
onto = get_ontology('onto.owl')
onto.imported_ontologies.append(emmo)
onto.sync_attributes()
onto.sync_reasoner()
... owlready2.base.OwlReadyJavaError: Java error message is: ... Could not load imported ontology: <https://emmc.info/emmo-inferred>.

I believe that the URI needs to be set differently (I believe should be more like http://www.emmc.info/emmc-csa/... ). I can get further if overloading base_iri='emmo-inferred.owl' in get_ontology() with e.g. base_iri='emmo-core.owl'. It would be also beneficial having ontology source on a local disk since many computers run on intranet without internet access.

Best regards. Vit

**Comment by jesper-friis** [comment]
This should have been fixed in branch 1.0.0
