### ISSUE TITLE
Clean up demo, examples and docs

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMO-python#193]
Move `demo` and `examples` under `docs` and clean up the structure surrounding it.

**Comment by CasperWA** [comment]
@francescalb @jesper-friis So what do you think? Should we move the `demo` and `examples` folders into the `docs` folder and make it solely a part of the documentation? Or do you think it might still be nice to have one or both of these folder in the root and separate from the documentation for users to play around with if they `git clone` the repository?

**Comment by francescalb** [comment]
I see your point of separating them out into the documentation only. I often look for examples in the repo itself, but that is usually in not very mature packages. I am not sure what we should do here as I like cloning myself, but I am not sure if that is the best way to work.

**Comment by CasperWA** [comment]
> I see your point of separating them out into the documentation only. I often look for examples in the repo itself, but that is usually in not very mature packages. I am not sure what we should do here as I like cloning myself, but I am not sure if that is the best way to work.

We can also do what I've set up in the current draft PR #222, namely to symlink the `demo` and `examples` folders in the `docs` folder in order to include them in the documentation, but still keep them in the root folder.

However, I am unsure it this is what we want.
If you use the workflow of "`git clone` -> check repo examples" in general, then it would be more helpful to have a root `examples` folder. However, I'd argue that perhaps most of these things should either be learned through the documentation or available Jupyter Notebooks, e.g., where one could test out and learn how to use the package and the tools?
The latter could be done with [mybinder](https://mybinder.org/) or a page of simple setup instructions in the documentation for how to install and start a Jupyter server in the correct "demo/examples" folder location.

In this way the demonstrations and examples are consciously labeled as "documentation".

Also, what is the difference between demonstrations (demo) and examples here? Isn't it essentially the same thing? Or is "demo" more of an example to use multiple tools at once, where examples are tool-specific?

**Comment by francescalb** [comment]
I agree with your points. I just have to work differently 😊 And it nice to put all documentation together.
I think demos and examples can be joined. Demos are older, but in principle they can be put together I think.
