### ISSUE TITLE
Require rdflib>5.0.0?

### ISSUE THREAD

**Issue by francescalb** [emmo-repo/EMMO-python#206]
@jesper
In the README there is a warning about serialisation of turtle with older versions of rdflib. Can we change requirements to be rdflib>5.X so that this is never an issue?

**Comment by CasperWA** [comment]
As a note, a discussion has taken place about this in #212. For me the deciding comment was [this](https://github.com/emmo-repo/EMMO-python/pull/212#issuecomment-921229187), which underlines that while the use case still exists for installing and using EMMOntoPy using system-packages, then the latest of these standards should be supported. For RDFLib this is v4.2.1.

**Comment by jesper-friis** [comment]
Agree with Casper. We give people the option to use old versions of rdflib provided with their distribution, but at the same time warn them about a possible issues. 

Maybe we could update the README file to suggest virtualenv and pip (as the preferred option) instead of cloning from master.

**Comment by CasperWA** [comment]
> Maybe we could update the README file to suggest virtualenv and pip (as the preferred option) instead of cloning from master.

These things are not mutually exclusive. The virtualenv+pip setup is merely a way to isolate a Python interpreter, environment variables, etc. to ensure especially Python packages are not mixed with the system-wide packages.
It also allows one to run different but dedicated Python versions alongside each other in each of the created virtual environments, i.e., one for Python 2.7 and one for Python 3.10, e.g.

Whether one wants to then install EMMOntoPy system-wide or in a virtualenv is separate from installing it either via GitHub (`git clone` or `pip install git+https:// ...`) or via PyPI (`pip install EMMOntoPy`).

In the end, yes, installation instructions for various paths would be excellent to include in the documentation :)
