### ISSUE TITLE
Circular reference from Owlready2

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMO-python#210]
A `sqlite3.OperationalError: circular reference: prelim1_objs` is thrown when running `DocPP.process()`.
This error is thrown from Owlready2 and doesn't seem to be directly related to this package, but never the less affects it severely.

An example of the error message can be seen in [this CI run](https://github.com/emmo-repo/EMMO-python/pull/208/checks?check_run_id=3599727802#step:6:28)

**Comment by francescalb** [comment]
Seems like a new issue with owlready0.34? If so we can continue with the list of owlready packages to disregard in the requirements.
