### ISSUE TITLE
Consider MarkDown header styling

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMO-python#231]
# EMMOntoPy - Python library for working with ontologies
EMMOntoPy is a Python library for woking with ontologies in general and the Elemental Multiperspective Material Ontology in particular.

_Originally posted by @jesper-friis in https://github.com/emmo-repo/EMMO-python/pull/222#discussion_r717284193_

As outlined in this review comment @jesper-friis prefers the underlining header-styling.

In my opinion it is not to be preferred simply due to the limitations of the header level that's possible with that styling; there is no possibility to go past level 2 headers with this styling.

However, we could definitely do mixed styling if this is so desired, as long as we, again, in my opinion, do it consequently for all files.

**Comment by jesper-friis** [comment]
I see that we have ended up with the MarkDown hash header style. Lets stay with that (even though I personally prefer the mixed header styling)
