### ISSUE TITLE
Update public documentation to new framework

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMO-python#234]
I've set up the new framework and documentation in the [`test-mike`](https://github.com/emmo-repo/EMMO-python/tree/test-mike) branch, updated it with the old documentation as well as a correct versioning for the current EMMOntoPy/EMMO-python package and EMMO PyPI version.

In order to "publish" it, it should be force pushed to the `gh-pages` branch, which will automagically publish the new documentation style.

I've tested the workflow for updating and publishing new versions locally, it seems stable to keep the old documentation and more.
I will document this workflow both in the form of the CD as well as actual documentation.

@jesper-friis and @francescalb please let me know here whether you are okay to "publish" the new documentation framework.
You can test it out first by doing the following:

```console
/path/to/EMMO-python$ git fetch origin && git checkout master
/path/to/EMMO-python$ git pull
/path/to/EMMO-python$ pip install -U -e .[docs]
/path/to/EMMO-python$ mike serve -r origin -b test-mike
Starting server at http://localhost:8000/
Press Ctrl+C to quit.
```

And then go to [http://localhost:8000](http://localhost:8000).

---

To dos:
- [x] Fix landing page logos (issue: #233) (PR: #235)
- [x] Fix EMMO acronym everywhere in the package (issue: #230) (PR: #238)
- [x] Update `test-mike` branch with fixes.
- [x] Force push `test-mike` to `gh-pages`, publishing the new documentation framework.

**Comment by francescalb** [comment]
I think it is almost fine to publish it, after we have changed the EMMO-acronym and fixed the sized of the contributing project logos. I would like the first page to look more or less correct at least...

**Comment by CasperWA** [comment]
> I think it is almost fine to publish it, after we have changed the EMMO-acronym and fixed the sized of the contributing project logos. I would like the first page to look more or less correct at least...

Good idea.
I've added these two points to the OP as "to do"s with references to their respective issues and PR(s).

**Comment by CasperWA** [comment]
The new documentation framework has now officially been put in place: https://emmo-repo.github.io/EMMO-python 🎉 🌟
