### ISSUE TITLE
Overwriting `get_triples()` method

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMO-python#280]
This method was erroneously overwritten in #246 for `ontopy.ontology.Ontology`. The method name should be changed.

**Comment by CasperWA** [comment]
As a note, @francescalb, should the unabbreviate function go through `self.world.get_triples()` or `self.get_triples()`? Or is this the same?

**Comment by francescalb** [comment]
It is actually the same. Both World and Ontology inherit from _Graphmanager in owlready2, and get_triples is defined as a function of _Graphmanager.

**Comment by CasperWA** [comment]
Great - that's what I could reason myself to as well, I just wanted to make sure - do you mind if I change from `self.world.get_triples()` to `self.get_triples()` then? Since only the latter is used elsewhere in the file already?

**Comment by francescalb** [comment]
No, that is smart. This explains my initial mistake as well. I found get_triples() in world and did not check well enough if it was defined in ontology.
