### ISSUE TITLE
ReadTheDocs

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMO-python#288]
Should the [`.readthedocs.yml`](https://github.com/emmo-repo/EMMO-python/blob/master/.readthedocs.yml) file be removed?
Is ReadTheDocs used by this repository?
Is the documentation published on ReadTheDocs or is this a configuration file to be used with OntoDoc?

**Comment by jesper-friis** [comment]
Yes, I think it can be removed.
