### ISSUE TITLE
get_by_label crash  if not str

### ISSUE THREAD

**Issue by sygout** [emmo-repo/EMMO-python#311]
the function get_by_label does not check the type of the label provided. it then crashes if a float is provided

this case appeared because when reading from an Excel sheet the list of prefLabel, an empty cell is read as a float (NaN).

**Comment by francescalb** [comment]
Do you think we should check if label is str and return a TypeError if not?

**Comment by sygout** [comment]
Yes it could be a first step.

Later I think that we should test if the submitted string is a valid label if there are rules for that.

**Comment by francescalb** [comment]
That we already do. If you ask for a label to does not exist it return NoSuchLabelError.

**Comment by francescalb** [comment]
closed with #312
