### ISSUE TITLE
permission denied when working with temporary file

### ISSUE THREAD

**Issue by sygout** [emmo-repo/EMMO-python#313]
the following code creates a problem on Windows:

´´´
with tempfile.NamedTemporaryFile(suffix=".owl") as handle:
                super().save(file=handle.name, format="rdfxml", **kwargs)
                graph = rdflib.Graph()
                graph.parse(handle.name, format="xml")
                graph.serialize(destination=filename, format=format)
´´´

It is related to an issue with tempfile library. See for example discussion: https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file

Similar issue might be present every time ontopy tries to work with tempfile.

**Comment by jesper-friis** [comment]
The nice thing with the `with tempfile.NamedTemporaryFile(suffix=".owl") as handle:` clause is that it deletes the temporary file when leaving it. Won't adding the argument `mode="w"` to tempfile.NamedTemporaryFile solve the issue?
