### ISSUE TITLE
What are the applications of EMMO for materials informatics?

### ISSUE THREAD

**Issue by sgbaird** [emmo-repo/EMMO-python#325]
It's a neat concept, but I'm having trouble getting a concrete idea of how a materials data scientist might go about using EMMO. For example, can this be considered as a nested classification scheme? Does it have things like periodic elements or space groups embedded within? Also, how were these ontologies made? Manually (human intuition)? Using natural language processing?

**Comment by jesper-friis** [comment]
EMMO is intended to be a common language for applied sciences. Among others, it facilitates semantic search, interoperability and data documentation.

EMMO itself does not include space groups, but the CIF and crystallography domain ontologies include space group as an ontological concept. 

EMMO is made by humans.
