### ISSUE TITLE
Avoid infinite recursion when loading catalog file

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO-python#369]
Loading the datamodel ontology at https://github.com/emmo-repo/datamodel-ontology results in RecursionError

**Comment by francescalb** [comment]
I do not get a recursion errorr, but that it cannot find the imported ontologies, even though they are correctly resolved in the catalog file. 

onto =  get_ontology('https://raw.githubusercontent.com/emmo-repo/datamodel-ontology/master/datamodel.ttl').load()

gives:
urllib.error.HTTPError: HTTP Error 404: https://raw.githubusercontent.com/emmo-repo/datamodel-ontology/master/data.ttl: https://raw.githubusercontent.com/emmo-repo/datamodel-ontology/master/data.ttl: Not Found

even though the import is stated as 
 <http://emmo.info/emmo/1.0.0-beta4/perspectives/data>

and we have in the catalog-file:
<uri name="http://emmo.info/emmo/1.0.0-beta4/perspectives/data"              uri="https://raw.githubusercontent.com/emmo-repo/EMMO/1.0.0-beta4/perspectives/data.ttl"/>

apparently it does not check in the catalog-file.
