### ISSUE TITLE
Edge without label crash the graph creation

### ISSUE THREAD

**Issue by sygout** [emmo-repo/EMMO-python#397]
In the examples of visualization in Jupyter, the code crash here:
cytograph = cytoscapegraph(graph, onto=onto, infobox='right')

In the function cytoscapegraph, the graph is explored to go through the edges list:
data = cytoscape_data(pydot_graph)["elements"]
for datum in data["edges"]:
      datum["data"]["label"]

There is no test that a key "label" is present.
Some of edges do not  have label: {'data': {'arrowhead': 'empty', 'source': 'SINTEFPerson', 'target': 'Person', 'key': 0}}
A fix is to make a test         if "label" in datum["data"]: and ignore all the edges without label

**Comment by francescalb** [comment]
This is due to graphs in in OntoGraoh no longer being generated with edgelabels=True as default.

To do: Change to edgelabel=True in the example jupyter lab notebook, 

and return an error that explains to do if labels are missing.
