### ISSUE TITLE
Pre.commit failed with ontology.py

### ISSUE THREAD

**Issue by sygout** [emmo-repo/EMMO-python#415]
I got a problem with pre.commit for ontology.py related to pylint.

Error message are like:
Parameter 'fileobj' has been renamed to 'filename' in overridden 'Ontology.load' methodPylint(W0237:arguments-renamed)

**Comment by francescalb** [comment]
Seems to be working now, so I close this.

**Comment by sygout** [comment]
Was it tested on both Linux and Windows (just in case there are OS differences)?

**Comment by francescalb** [comment]
I do not get the same error anywhere. Can you reproduce it? If not I think we should close it..

**Comment by sygout** [comment]
Should I test on branch master?

**Comment by francescalb** [comment]
yes, or make a new branch out of master.

**Comment by sygout** [comment]
tested and no complain from pylint
