### ISSUE TITLE
excel2onto: not all relations are included in the generated ontology

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO-python#457]
* When creating the [microstructure domain ontology](https://github.com/emmo-repo/domain-microstructure) from [2022-09-02-microstructure.xlsx](https://github.com/emmo-repo/EMMO-python/files/9482416/2022-09-02-microstructure.xlsx), the `inverse(hasHolisticSpatialPart) min 2 Grain` restriction of `GrainBoundary` is added correctly, while the corresponding restrictions for `Boundary` and `DualBoundary` are missing. 
*

**Comment by francescalb** [comment]
Moved  the added_rows line back and made a new counter for all_added_rows, including all loops. 
The added_rows is used to check if there has been a change to stop a recurring loop, while all_added_rows will make sure that 
restrictions are tested for all added rows at the end. 

Also, note that there is an error in the excelfile: Microstructure added as concept but MicroStructure used in restrictions for Precipitate. Finally, I assume that you want to use Pore from EMMO, but Pore is not currently defined in the imported EMMO-beta4.
