### ISSUE TITLE
Include all annotations in .get_annotations()

### ISSUE THREAD

**Issue by francescalb** [emmo-repo/EMMO-python#50]
Currently, only 'comment's are returned in get_annotations. 
It would be nice to get other annotations such as 'elucidation' etc

**Comment by jesper-friis** [comment]
I think it works. For me the following returns both 'elucidation' and 'comment':

    from emmo import get_ontology
    emmo = get_ontology()
    emmo.load()
    emmo.Holistic.get_annotations()

**Comment by francescalb** [comment]
I agree
