### ISSUE TITLE
excelparser - enable object properties creation

### ISSUE THREAD

**Issue by JoanaFMorgado** [emmo-repo/EMMO-python#587]
Hello,

In our project we would like enable the generation of new OWL object properties (subProperties of a EMMO property) hierarchies from the excel file. How could we do it using ontopy.excelparser?

_e.g._: hasMode, hasMethod, hasProtocol as new subProperties of a EMMO class.

![image (3)](https://user-images.githubusercontent.com/45874338/233119646-3fbd709a-cd67-43c5-a188-545ed9ab1f50.png)

Thank you so much!
@yoavnash @pierluigidelnostro @francescalb @MaksimZapara

**Comment by francescalb** [comment]
Hi, I will look into this after next week.
