### ISSUE TITLE
Unable to use the vertical interoperability demo .py files

### ISSUE THREAD

**Issue by Lexachoc** [emmo-repo/EMMO-python#66]
Hello, 

I'm using Pycharm to run the codes, my OS is win10, and the Python version is 3.8.3.
When running the "define_ontology.py" file, it shows the error message:

> Traceback (most recent call last):
>   File "C:/Users/Choc/PycharmProjects/pythonProject/define_ontology.py", line 196, in <module>
>     class WeldedComponent(emmo.Component):
>   File "C:\Users\Choc\anaconda3\lib\site-packages\emmo\ontology.py", line 110, in __getattr__
>     attr = self.get_by_label(name)
>   File "C:\Users\Choc\anaconda3\lib\site-packages\emmo\ontology.py", line 420, in get_by_label
>     raise NoSuchLabelError('Ontology "%s" has no such label: %s' % (
> emmo.ontology.NoSuchLabelError: Ontology "emmo-inferred" has no such label: Component

I actually have no idea how to deal with that, so I comment out the "class WeldedComponent(emmo.Component):" part first in order to make it runs well. Then, I keep running the "plot_ontology.py" file, but it still shows error message no matter the  "define_ontology.py" file runs well or not:

> Traceback (most recent call last):
>   File "C:/Users/Choc/PycharmProjects/pythonProject/plot_ontology.py", line 17, in <module>
>     graph = onto.get_graph(entities=classes, relations='all',
>   File "C:\Users\Choc\anaconda3\lib\site-packages\emmo\ontology.py", line 672, in get_graph
>     return OntoGraph(self, **kwargs)
>   File "C:\Users\Choc\anaconda3\lib\site-packages\emmo\graph.py", line 227, in __init__
>     self.add_entities(entities=entities, relations=relations,
>   File "C:\Users\Choc\anaconda3\lib\site-packages\emmo\graph.py", line 242, in add_entities
>     self.add_nodes(entities, nodeattrs=nodeattrs, **attrs)
>   File "C:\Users\Choc\anaconda3\lib\site-packages\emmo\graph.py", line 303, in add_nodes
>     self.add_node(name, nodeattrs=nodeattrs, **attrs)
>   File "C:\Users\Choc\anaconda3\lib\site-packages\emmo\graph.py", line 297, in add_node
>     self.dot.node(label, label=label, **kw)
>   File "C:\Users\Choc\anaconda3\lib\site-packages\graphviz\dot.py", line 130, in node
>     name = self._quote(name)
>   File "C:\Users\Choc\anaconda3\lib\site-packages\graphviz\lang.py", line 72, in quote
>     if is_html_string(identifier) and not isinstance(identifier, NoHtml):
> TypeError: expected string or bytes-like object

Any advice is appreciated!

**UPDATE:** I try to run these codes on Jupyter Notebook. And the "define_ontology.py" file runs well (I have no idea why). 
But the "plot_ontology.py" file still shows the same TypeError😥. Please help.

**Comment by jesper-friis** [comment]
Hi Lexachoc,
the reason for this error is that EMMO has evolved and switched from rdfs:label to skos:prefLabel. I pushed a quick fix to the branch issue66-fix-demo.

**Comment by Lexachoc** [comment]
@jesper-friis Thank you so much for your quick reply and fix.
That is really helpful!
