### ISSUE TITLE
Ontograph: Include multiple parents/inheritance

### ISSUE THREAD

**Issue by francescalb** [emmo-repo/EMMO-python#86]
Branches with several parents end up floating alone without connection to either of their parents in ontograph

**Comment by francescalb** [comment]
@jesper-friis I do not remember the example that we had for this. Do you?

**Comment by francescalb** [comment]
@jesper-friis I was not able to reproduce this error. I suggest to close this issue and reopen it if it occurs again, with example.

**Comment by jesper-friis** [comment]
Agree
